services:
  # PostgreSQL database
  db:
    image: postgres:17-alpine
    container_name: ffh_postgres_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for cahce and sessions
  redis:
    image: redis:7-alpine
    container_name: ffh_redis_dev
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend Django
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    user: "${UID:-1000}:${GID:-1000}"
    container_name: ffh_backend_dev
    volumes:
      - ./backend:/app
      - media_files:/app/media
      - static_files:/app/staticfiles
    env_file:
      - .env
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=config.settings.development
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - REDIS_URL=redis://${REDIS_HOST}:${REDIS_PORT}/0
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend
      - CORS_ALLOWED_ORIGINS=http://localhost:5173,http://127.0.0.1:5173
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  # Frontend React
  frontend:
    build:
      context: ./frontend
      target: development
      dockerfile: Dockerfile
    container_name: ffh_frontend_dev
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api
      - VITE_APP_NAME=FamilyFinanceHub
      - NODE_ENV=development
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped
    command: npm run dev

  # Celery Worker (Async tasks)
  celery-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    user: "${UID:-1000}:${GID:-1000}"
    container_name: ffh_celery_worker_dev
    volumes:
      - ./backend:/app
      - media_files:/app/media
    env_file:
      - .env
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=config.settings.development
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - REDIS_URL=redis://${REDIS_HOST}:${REDIS_PORT}/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    command: celery -A config worker --loglevel=info
    profiles:
      - celery

  # Celery Beat (tasks schedules)
  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    user: "${UID:-1000}:${GID:-1000}"
    container_name: ffh_celery_beat
    volumes:
      - ./backend:/app
    env_file:
      - .env
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=config.settings.development
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - REDIS_URL=redis://${REDIS_HOST}:${REDIS_PORT}/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    command: celery -A config beat --loglevel=info
    profiles:
      - celery

volumes:
  postgres_data:
  redis_data:
  media_files:
  static_files:

networks:
  default:
    name: ffh_network_dev
